version: '3'

services: 
  db:
    image: postgres:11.2
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=telegram
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local